# Generated by Django 5.1.7 on 2025-05-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='return_flight',
            new_name='flight_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='luggage',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='outbound_flight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travelers',
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='outbound_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
