# Generated by Django 5.1.7 on 2025-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_return_flight_booking_flight_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='query_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
