# Generated by Django 5.1.7 on 2025-05-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userquery_query_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightdelay',
            old_name='flight_id',
            new_name='flight_number',
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='delay_duration',
            field=models.IntegerField(),
        ),
    ]
